const { createMySQLModel } = require('../../lib/mysqlDocumentModel');

module.exports = createMySQLModel('Event', {
  collectionName: 'events',
  timestamps: true,
  indexes: [['eventName'], ['event_title'], ['sportType'], ['eventType']],
  fieldTypes: {
    teamSizeMin: 'integer',
    teamSizeMax: 'integer',
    overall_champion_points: 'integer',
    runner_up_points: 'integer',
    news_highlight: 'text',
  },
  defaults: {
    eventName: '',
    category: '',
    sportType: 'Athletics',
    eventType: 'Individual',
    level: '',
    gender: 'Mixed',
    date: '',
    eventDate: 'TBA',
    eventTime: 'TBA',
    registrationStartDate: 'TBA',
    registrationEndDate: 'TBA',
    teamSizeMin: null,
    teamSizeMax: null,
    registrationStatus: 'Closed',
    event_title: '',
    event_level: '',
    event_date: '',
    venue: '',
    city: '',
    overall_champion: '',
    overall_champion_points: null,
    runner_up: '',
    runner_up_points: null,
    mens_individual_champion: '',
    mens_champion_institution: '',
    womens_individual_champion: '',
    womens_champion_institution: '',
    news_highlight: '',
  },
});
